name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: '24'

runs:
  using: composite
  steps:
    - name: Setup pnpm and Node.js
      uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      with:
        runtime: node@${{ inputs.node-version }}
        cache: true
