name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: '24'

runs:
  using: composite
  steps:
    - name: Setup pnpm and Node.js
      uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
      with:
        runtime: node@${{ inputs.node-version }}
        cache: true
