ignoreWorkspaceRootCheck: true

packages:
  - website
  - packages/*

dedupePeers: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080 # 7 days

trustLockfile: true

minimumReleaseAgeExclude:
  - '@ocavue/eslint-config'
  - '@prosekit/*'
  - diffable-html-snapshot@0.3.0
  - prosemirror-splittable@1.0.0

# Enable "blockExoticSubdeps" and "overrides" to install packages from pkg.pr.new
# pkg.pr.new build of prosekit/prosekit#1700 (triggerAutocomplete)
blockExoticSubdeps: false
overrides:
  '@prosekit/pm': https://pkg.pr.new/@prosekit/pm@baea49458a34f914249332162b96d2fadc29f43c
  '@prosekit/react': https://pkg.pr.new/@prosekit/react@baea49458a34f914249332162b96d2fadc29f43c
  '@prosekit/core': https://pkg.pr.new/@prosekit/core@baea49458a34f914249332162b96d2fadc29f43c
  '@prosekit/extensions': https://pkg.pr.new/@prosekit/extensions@baea49458a34f914249332162b96d2fadc29f43c
  '@prosekit/web': https://pkg.pr.new/@prosekit/web@baea49458a34f914249332162b96d2fadc29f43c
