// @ts-nocheck
declare const styles = {
  'Root': '' as string,
  'Root': '' as string,
  'Root': '' as string,
  'Toolbar': '' as string,
  'Preview': '' as string,
  'Toolbar': '' as string,
  'Root': '' as string,
  'Toolbar': '' as string,
  'Root': '' as string,
  'Toolbar': '' as string,
  'Toolbar': '' as string,
  'Trigger': '' as string,
  'TriggerIcon': '' as string,
  'CopyButton': '' as string,
  'Positioner': '' as string,
  'Popup': '' as string,
  'SearchRow': '' as string,
  'Search': '' as string,
  'Empty': '' as string,
  'Empty': '' as string,
  'List': '' as string,
  'Item': '' as string,
  'ItemIndicator': '' as string,
  'ItemText': '' as string,
} as const;
export default styles;
