// @ts-nocheck
declare const styles = {
  'Positioner': '' as string,
  'Popup': '' as string,
  'Row': '' as string,
  'Preview': '' as string,
  'Actions': '' as string,
  'Url': '' as string,
  'Button': '' as string,
  'Icon': '' as string,
  'PreviewBody': '' as string,
  'Title': '' as string,
  'Host': '' as string,
  'Description': '' as string,
  'ReplaceRow': '' as string,
  'ReplaceButton': '' as string,
  'Skeleton': '' as string,
  'SkeletonHeader': '' as string,
  'SkeletonLine': '' as string,
  'SkeletonLineShort': '' as string,
  'pulse': '' as string,
  'Form': '' as string,
  'Field': '' as string,
  'Input': '' as string,
  'FormActions': '' as string,
  'RemoveButton': '' as string,
  'UseTitleButton': '' as string,
  'SaveButton': '' as string,
} as const;
export default styles;
