import { describe, expect, it } from 'vitest'

import { codeBlockLanguages } from './code-block-languages.ts'

describe('codeBlockLanguages', () => {
  it('lists the supported languages as `value → label` pairs', () => {
    const pairs = codeBlockLanguages.map(({ value, label }) => `${value} -> ${label}`)
    expect(pairs).toMatchInlineSnapshot(`
      [
        "c -> C",
        "c++ -> C++",
        "cql -> CQL",
        "css -> CSS",
        "go -> Go",
        "html -> HTML",
        "java -> Java",
        "javascript -> JavaScript",
        "jinja -> Jinja",
        "json -> JSON",
        "jsx -> JSX",
        "less -> LESS",
        "liquid -> Liquid",
        "mariadb sql -> MariaDB SQL",
        "markdown -> Markdown",
        "ms sql -> MS SQL",
        "mysql -> MySQL",
        "php -> PHP",
        "plsql -> PLSQL",
        "postgresql -> PostgreSQL",
        "python -> Python",
        "rust -> Rust",
        "sass -> Sass",
        "scss -> SCSS",
        "sql -> SQL",
        "sqlite -> SQLite",
        "tsx -> TSX",
        "typescript -> TypeScript",
        "webassembly -> WebAssembly",
        "xml -> XML",
        "yaml -> YAML",
        "apl -> APL",
        "pgp -> PGP",
        "asn.1 -> ASN.1",
        "asterisk -> Asterisk",
        "brainfuck -> Brainfuck",
        "cobol -> Cobol",
        "c# -> C#",
        "clojure -> Clojure",
        "clojurescript -> ClojureScript",
        "closure stylesheets (gss) -> Closure Stylesheets (GSS)",
        "cmake -> CMake",
        "coffeescript -> CoffeeScript",
        "common lisp -> Common Lisp",
        "cypher -> Cypher",
        "cython -> Cython",
        "crystal -> Crystal",
        "d -> D",
        "dart -> Dart",
        "diff -> diff",
        "dockerfile -> Dockerfile",
        "dtd -> DTD",
        "dylan -> Dylan",
        "ebnf -> EBNF",
        "ecl -> ECL",
        "edn -> edn",
        "eiffel -> Eiffel",
        "elm -> Elm",
        "erlang -> Erlang",
        "esper -> Esper",
        "factor -> Factor",
        "fcl -> FCL",
        "forth -> Forth",
        "fortran -> Fortran",
        "f# -> F#",
        "gas -> Gas",
        "gherkin -> Gherkin",
        "groovy -> Groovy",
        "haskell -> Haskell",
        "haxe -> Haxe",
        "hxml -> HXML",
        "http -> HTTP",
        "idl -> IDL",
        "json-ld -> JSON-LD",
        "julia -> Julia",
        "kotlin -> Kotlin",
        "livescript -> LiveScript",
        "lua -> Lua",
        "mirc -> mIRC",
        "mathematica -> Mathematica",
        "modelica -> Modelica",
        "mumps -> MUMPS",
        "mbox -> Mbox",
        "nginx -> Nginx",
        "nsis -> NSIS",
        "ntriples -> NTriples",
        "objective-c -> Objective-C",
        "objective-c++ -> Objective-C++",
        "ocaml -> OCaml",
        "octave -> Octave",
        "oz -> Oz",
        "pascal -> Pascal",
        "perl -> Perl",
        "pig -> Pig",
        "powershell -> PowerShell",
        "properties files -> Properties files",
        "protobuf -> ProtoBuf",
        "pug -> Pug",
        "puppet -> Puppet",
        "q -> Q",
        "r -> R",
        "rpm changes -> RPM Changes",
        "rpm spec -> RPM Spec",
        "ruby -> Ruby",
        "sas -> SAS",
        "scala -> Scala",
        "scheme -> Scheme",
        "shell -> Shell",
        "sieve -> Sieve",
        "smalltalk -> Smalltalk",
        "solr -> Solr",
        "sml -> SML",
        "sparql -> SPARQL",
        "spreadsheet -> Spreadsheet",
        "squirrel -> Squirrel",
        "stylus -> Stylus",
        "swift -> Swift",
        "stex -> sTeX",
        "latex -> LaTeX",
        "systemverilog -> SystemVerilog",
        "tcl -> Tcl",
        "textile -> Textile",
        "tiddlywiki -> TiddlyWiki",
        "tiki wiki -> Tiki wiki",
        "toml -> TOML",
        "troff -> Troff",
        "ttcn -> TTCN",
        "ttcn_cfg -> TTCN_CFG",
        "turtle -> Turtle",
        "web idl -> Web IDL",
        "vb.net -> VB.NET",
        "vbscript -> VBScript",
        "velocity -> Velocity",
        "verilog -> Verilog",
        "vhdl -> VHDL",
        "xquery -> XQuery",
        "yacas -> Yacas",
        "z80 -> Z80",
        "mscgen -> MscGen",
        "xù -> Xù",
        "msgenny -> MsGenny",
        "vue -> Vue",
        "angular template -> Angular Template",
      ]
    `)
  })
})
