/** Human-readable descriptions of the editor's formatting and heading shortcuts. */
export const EDITOR_KEY_BINDINGS = {
  'Mod-b': 'Bold',
  'Mod-i': 'Italic',
  'Mod-e': 'Inline code',
  'Mod-Shift-x': 'Strikethrough',
  'Mod-Shift-h': 'Highlight',
  'Mod-k': 'Link',
  'Mod-Shift-k': 'Insert a wikilink',
  'Mod-Shift-v': 'Paste without formatting',
  'Mod-1': 'Heading 1',
  'Mod-2': 'Heading 2',
  'Mod-3': 'Heading 3',
  'Mod-4': 'Heading 4',
  'Mod-5': 'Heading 5',
  'Mod-6': 'Heading 6',
  'Mod-.': 'Fold or unfold a bullet',
  'Mod-Enter': 'Follow the link under the caret, or cycle a checkbox task',
  'Mod-Shift-Enter': 'Cycle a circle checkbox task',
  'Mod-Shift-7': 'Ordered list',
  'Mod-Shift-8': 'Bullet list',
  'Mod-Shift-9': 'Checkbox task list',
  'Alt-ArrowUp': 'Move the block or list item up',
  'Alt-ArrowDown': 'Move the block or list item down',
  'Meta-ArrowUp': 'Move the caret to the document start',
  'Meta-ArrowDown': 'Move the caret to the document end',
  'Shift-Meta-ArrowUp': 'Select to the document start',
  'Shift-Meta-ArrowDown': 'Select to the document end',
  Escape: 'Collapse the selection',
} as const
