/**
 * Human-readable descriptions of the editor's formatting and heading shortcuts.
 */
export const EDITOR_KEY_BINDINGS = {
  'Mod-b': 'Bold',
  'Mod-i': 'Italic',
  'Mod-e': 'Inline code',
  'Mod-Shift-x': 'Strikethrough',
  'Mod-Shift-h': 'Highlight',
  'Mod-k': 'Link',
  'Mod-Shift-k': 'Insert a wikilink',
  'Mod-Alt-1': 'Heading 1',
  'Mod-Alt-2': 'Heading 2',
  'Mod-Alt-3': 'Heading 3',
  'Mod-Alt-4': 'Heading 4',
  'Mod-Alt-5': 'Heading 5',
  'Mod-Alt-6': 'Heading 6',
  'Mod-.': 'Fold or unfold a bullet',
  'Shift-Enter': 'Insert a line break, or leave a code block from its end',
  'Mod-Enter': 'Follow the link under the caret, or cycle a checkbox task',
  'Mod-Shift-Enter': 'Cycle a circle checkbox task',
  'Mod-Shift-7': 'Ordered list',
  'Mod-Shift-8': 'Bullet list',
  'Mod-Shift-9': 'Checkbox task list',
  'Alt-ArrowUp': 'Move the block or list item up',
  'Alt-ArrowDown': 'Move the block or list item down',
  'Mod-ArrowUp': 'Move the caret to the document start',
  'Mod-ArrowDown': 'Move the caret to the document end',
  'Mod-Shift-ArrowUp': 'Select to the document start',
  'Mod-Shift-ArrowDown': 'Select to the document end',
  Escape: 'Collapse the selection',
} as const
